<section id="about">
    <h2 class="text-accent">INFINITY STUDIO</h2>
    <p>
        AFFORDABLE DIGITAL SOLUTIONS FOR SMALL AND MEDIUM BUSINESSES.<br> INFINITY STUDIO HELPS COMPANIES AUTOMATE PROCESSES, ACCELERATE GROWTH, AND INCREASE PROFITS WITH MODERN IT SOLUTIONS. WE CREATE WEBSITES, MOBILE APPLICATIONS, IMPLEMENT SMM STRATEGIES, AND DEVELOP BRANDING – QUICKLY, EFFICIENTLY, AND AT AN AFFORDABLE PRICE.
    </p>
    <p>
        WE FOCUS ON SMALL AND MEDIUM BUSINESSES, UNDERSTANDING THEIR NEEDS AND OFFERING EFFECTIVE AND BUDGET-FRIENDLY SOLUTIONS.
    </p>
    <p>
        INFINITY STUDIO IS ALREADY OPERATING AND READY FOR COLLABORATION! OUR WEBSITE IS CURRENTLY UNDER DEVELOPMENT, BUT WE ARE ALWAYS AVAILABLE AND READY TO DISCUSS YOUR PROJECTS.
    </p>
    <a href="/" class="button button--primary contact-us" data-modal="contactModal">
        contact us
        <svg class="button-arrow" width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M8.20312 3.51562L12.4219 7.73438M12.4219 7.73438L8.20312 11.9531M12.4219 7.73438H2.57812" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
    </a>
</section>